### ISSUE TITLE
Issue with PvZ Battle for Neighborville

### ISSUE THREAD

**Issue by Booklordofthedings** [NicknineTheEagle/Frostbite-Scripts#16]
So I wanted to try it out on that game, but it didn't work.
I don't know if it is supposed to work, but you said in a previous thread that it works with PvZ
the issue produced is as follows

`Traceback (most recent call last):
  File "D:\TheDirectory\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 269, in <module>
    dumpRoot(dataDir,patchDir,targetDirectory)
  File "D:\TheDirectory\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 172, in dumpRoot
    dump(patchedName,fname,outPath)
  File "D:\TheDirectory\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 64, in dump
    toc=dbo.readToc(tocPath)
  File "D:\TheDirectory\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dbo.py", line 271, in readToc
    return DbObject(unXor(tocPath))
  File "D:\TheDirectory\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dbo.py", line 260, in __init__
    raise Exception("Unhandled DB object type 0x%02x at 0x%08x." % (self.typ,f.tell()))
Exception: Unhandled DB object type 0x00 at 0x00000002.`

Before that it outputted this: 
Extracting main game...
layout.toc
Win32\characters.toc

I copyed the oo2core_6.dll file into the thirdparty directory, but it may have errored due to the fact that it looks like a newer version of it.
There also is a oo2ext_6.dll file which might be a extention or something
(I don't know that much about encryption)
but putting it into the thirdparty folder didn't work and it still output the same error.
I also didn't download any libary, so I might be missing some, but I cant figure out if im missing it

**Comment by NicknineTheEagle** [comment]
This game uses the same structure as Anthem which is not supported yet. See https://github.com/NicknineTheEagle/Frostbite-Scripts/issues/5

**Comment by Booklordofthedings** [comment]
Misread it sorry, but thanks for the quick awnser
