### ISSUE TITLE
Error when trying to run fb3 dumper

### ISSUE THREAD

**Issue by FlashHit** [NicknineTheEagle/Frostbite-Scripts#28]
```
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py
Loading RES names...
Reading cat entries...
Reading patched cat entries...
Extracting DLC Xpack0...
Win32\XP0LevelsChunks.toc
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 211, in <module>
    dumpRoot(os.path.join(updateDir,dir,"Data"),patchDir,targetDirectory)
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 150, in dumpRoot
    dump(fname,None,outPath)
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\dumper.py", line 129, in dump
    payload.noncasChunkPayload(entry,targetPath,sbPath)
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\payload.py", line 251, in noncasChunkPayload
    decompressPayload(sourcePath,entry.get("offset"),entry.get("size"),None,targetPath)
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\payload.py", line 110, in decompressPayload
    decompressBlock(f,f2)
  File "C:\Users\Administrator\Downloads\Frostbite-Scripts-master\Frostbite-Scripts-master\frostbite3\payload.py", line 92, in decompressBlock
    dstBuf=zlib.decompress(srcBuf)
zlib.error: Error -3 while decompressing data: incorrect header check
```

**Comment by NicknineTheEagle** [comment]
What game (and platform) are you extracting?

**Comment by FlashHit** [comment]
BF4 Windows

**Comment by FlashHit** [comment]
would be nice if you could text me in discord: Bree_Arnold#5117

**Comment by NicknineTheEagle** [comment]
Unable to reproduce on the latest master. Validate your game in Origin, your file are possibly corrupt.

**Comment by FlashHit** [comment]
I repaired the game in origin and now it seems to work. Thank you.
