### ISSUE TITLE
Need for Speed The Run [DLC]

### ISSUE THREAD

**Issue by LU4117** [NicknineTheEagle/Frostbite-Scripts#32]
Error with TOC files (.toc) from Xbox360 DLC files, "Italian car pack", 
with xboxdecompress.exe in the thirdparty folder
[https://i.imgur.com/DDCOyDc.png](url)

text:
Traceback (most recent call last):
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 331, in <module>
    dumpRoot(dataDir,patchDir,targetDirectory)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 291, in dumpRoot
    dump(fname,outPath)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 109, in dump
    unpatchedSb=openSbFile(baseTocPath[:-3]+"sb")
TypeError: 'NoneType' object is not subscriptable

This is all i get while using the latest version from the repo.

**Comment by LU4117** [comment]
I have the DLC files ready to share just in case

**Comment by NicknineTheEagle** [comment]
Sounds like you're missing game files that are required to do the extraction.

**Comment by LU4117** [comment]
Alright it seems you're right, but it seems it takes a while to write a res table, an hour straight and the file still 1kb. 
I'm going to leave it running, because with PC one took some time, this might take more idk

**Comment by NicknineTheEagle** [comment]
You sure it's not finished already? If IDLE console is showing three arrows, that means the script is done.

**Comment by LU4117** [comment]
Yeah no nevermind, please ignore that (I deleted the comment)
My folder layout was wrong and it is doing stuff
I see something that's off I'll let you know

**Comment by LU4117** [comment]
During my first attempt, i set up my DLC location in BaseFolder/Update/Data/
Which during dump displayed the message of extracting dlc/ dlc scripts
it was brief and it started with the base game files after that.
But after the process i wasn't able to find any of the dlc content (.MeshSet or .ebx)


Next i tried the PC folder hierarchy which is BaseFolder/Update/Patch/Data.
it didn't displayed any message of extracting DLC content and it gets stuck in a decompressing loop with AudioSuperBoundle.toc
Now; closing xbdecompress.exe
will display this:
[https://i.imgur.com/JowPazr.png](url)

text:
layout.toc
XENON\AudioSuperBundle.toc
Traceback (most recent call last):
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 331, in <module>
    dumpRoot(dataDir,patchDir,targetDirectory)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 289, in dumpRoot
    dump(patchedName,outPath,fname,commonDatPath)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 109, in dump
    unpatchedSb=openSbFile(baseTocPath[:-3]+"sb")
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 249, in openSbFile
    return open(decSbPath,"rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\NFSTRDump\\NFSrun360x_patch\\temp\\Data\\XENON\\AudioSuperBundle.sb'

Don't tell me this requires other previous DLC aswell?
Is this a folder hierarchy issue from my part?

**Comment by NicknineTheEagle** [comment]
You've set up your folders incorrectly. Individual DLCs should each be in a separate subfolder in Update (*not* named Patch).

**Comment by LU4117** [comment]
i'll assume that it can have any name but Patch?

**Comment by NicknineTheEagle** [comment]
Correct.

**Comment by LU4117** [comment]
[https://i.imgur.com/1J5NMp7.png](url)

text:
Xenon\AudioSuperBundle.toc
Traceback (most recent call last):
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 327, in <module>
    dumpRoot(os.path.join(updateDir,dir,"Data"),patchDir,targetDirectory)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 291, in dumpRoot
    dump(fname,outPath)
  File "C:\Games\Need for Speed The Run\DumperNew\frostbite2\dumper.py", line 109, in dump
    unpatchedSb=openSbFile(baseTocPath[:-3]+"sb")
TypeError: 'NoneType' object is not subscriptable

my folder hierarchy
[https://i.imgur.com/gvfUJ3r.png](url)

**Comment by LU4117** [comment]
i have a feeling i need _every_ DLC or at least previous one

**Comment by NicknineTheEagle** [comment]
Your image links are broken, BTW.

**Comment by NicknineTheEagle** [comment]
Hmm, it looks DLC superbundles also reference base superbundles, I'll have too look into it.

**Comment by LU4117** [comment]
Ok, someone taught me how to dump with the content seen in the italian car pack, (not sure if i should go into depth about this)
but after obtaining the whole game dumped, i decided to use ebxtoasset.py with one of the textures ebx
but the final .dds seems to be a corrupted gibberish.

Things worth pointing out:

- This is Xenon (x360)
- I haven't tested it with PS3
- Hasn't been tested with a dump that doesn't contain the extra content
- Blender displays **some** of the PC/Dx converted textures as corrupted gibberish aswell, but in reality they are fine and image editor software like Paintdotnet can open and convert them properly. **(Still can't display Xenon textures)**
- The texture aspect ratio seems to match of what the UVs indicate, but resolution is much smaller

Altought irrelevant to the topic, ebxtotext.py works fine if you are wondering.

I'm not sure if i should create another Issue exclusive for this.

**Comment by auvy** [comment]
> Ok, someone taught me how to dump with the content seen in the italian car pack, (not sure if i should go into depth about this)
>
@LU4117 Man. How did you manage to do it? I've been spinning my wheels trying to dump stuff from Xenon.
(idk if it's appropriate to ask this on this issue but I'm just that desperate)

**Comment by mRally2** [comment]
> Ok, someone taught me how to dump with the content seen in the italian car pack, (not sure if i should go into depth about this) but after obtaining the whole game dumped, i decided to use ebxtoasset.py with one of the textures ebx but the final .dds seems to be a corrupted gibberish.
> 
> Things worth pointing out:
> 
> * This is Xenon (x360)
> * I haven't tested it with PS3
> * Hasn't been tested with a dump that doesn't contain the extra content
> * Blender displays **some** of the PC/Dx converted textures as corrupted gibberish aswell, but in reality they are fine and image editor software like Paintdotnet can open and convert them properly. **(Still can't display Xenon textures)**
> * The texture aspect ratio seems to match of what the UVs indicate, but resolution is much smaller
> 
> Altought irrelevant to the topic, ebxtotext.py works fine if you are wondering.
> 
> I'm not sure if i should create another Issue exclusive for this.

Could you upload somewhere the ebxtotext results of the Italian Pack?

**Comment by LU4117** [comment]
https://www.mediafire.com/file/yie8loqi2scwr1s/NFS_11_ITALIAN_DLC_CARS.zip/file
textures are compressed or corrupted

**Comment by mRally2** [comment]
Actually, could you upload the whole x360 version in ebxtotext format besides the ones from the DLC? I’m making some sort of a wiki about this game. You can check my repository. Also, do you mind sharing how you managed to extract the game avoiding the bug?

**Comment by LU4117** [comment]
Not sure if I can, but you have to

**Comment by LU4117** [comment]
Not sure if I can, I forgot the name of it
But basically the content from it was added in a previous patch, so you have to get that one instead

**Comment by LU4117** [comment]
1.1 update* I might have the container somewhere, and other tools, I'll have to dig

I'll still try to upload whole thing

**Comment by mRally2** [comment]
I see, that’s why you can find a bunch of strings related to the console exclusive challenge series events inside one of the language files of the Update folder on PC.

**Comment by mRally2** [comment]
> I'll still try to upload whole thing

Appreciate it

**Comment by LU4117** [comment]
https://www.mediafire.com/file/b9g6coiy1rnjs3q/XENON_NFSTHERUN_E_U11.rar/file
Audio, Presets, Vinyls, Cars all that stuff
side note: Leo already managed to read TR's VLT data years ago

**Comment by mRally2** [comment]
> https://www.mediafire.com/file/b9g6coiy1rnjs3q/XENON_NFSTHERUN_E_U11.rar/file Audio, Presets, Vinyls, Cars all that stuff side note: Leo already managed to read TR's VLT data years ago

That’s just a part of the Italian DLC extracted I believe. There should be a lot more stuff regarding Levels and such. Could you upload the whole X360 1.1 Update EBX folder? And yes, Leo did make a profile for The Run but he decided to keep it private for whatever reason.

**Comment by LU4117** [comment]
i don't have the hardware to do that, so i'll DM you the essentials and probably guide you

**Comment by NicknineTheEagle** [comment]
Extraction should be fixed in c03a11412ebb1ea16110cbd7f67ddc22bfbd9442.
